"""Initial migration.

Revision ID: 028cf2b5f73c
Revises: 
Create Date: 2020-11-03 20:21:40.770439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028cf2b5f73c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('dni', sa.String(length=30), nullable=False),
    sa.Column('dataEndDrivePermission', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('active', 'notActive'), nullable=False),
    sa.Column('creditCard', sa.String(length=30), nullable=False),
    sa.Column('availableMoney', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('user', 'support', 'admin', 'technical'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creditCard'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('motoid', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('totalTimeUsed', sa.Time(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('charge', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motos')
    op.drop_table('booking')
    op.drop_table('accounts')
    # ### end Alembic commands ###
