"""sdfdsf

Revision ID: 445bb14198ed
Revises: 
Create Date: 2020-10-28 21:26:38.282877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445bb14198ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('dni', sa.String(length=30), nullable=True),
    sa.Column('dataEndDrivePermission', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('', ''), nullable=True),
    sa.Column('creditCard', sa.String(length=30), nullable=True),
    sa.Column('availableMoney', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('user', 'support', 'admin', 'technical'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('charge', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('motoid', sa.Integer(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('totalTimeUsed', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['motoid'], ['motos.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('motos')
    op.drop_table('accounts')
    # ### end Alembic commands ###
